// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from hellodjinni.djinni

#import <Foundation/Foundation.h>
@class HDHelloDjinni;


@interface HDHelloDjinni : NSObject

+ (nullable HDHelloDjinni *)create;

- (nonnull NSString *)getHelloDjinni;

- (int32_t)getOne;

@end
